//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropCfe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminAccount
    {
        public int idAdmin { get; set; }
        public string taikhoanAdmin { get; set; }
        public string passAdmin { get; set; }
    }
}
