//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropCfe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanPham()
        {
            this.ctDonHangs = new HashSet<ctDonHang>();
        }
    
        public string maSP { get; set; }
        public string tenSP { get; set; }
        public string hinhSP { get; set; }
        public int giaBan { get; set; }
        public string calories { get; set; }
        public string fat { get; set; }
        public string Total { get; set; }
        public string percentFat { get; set; }
        public string Saturated { get; set; }
        public string percentSaturated { get; set; }
        public string Cholesterol { get; set; }
        public string percentCholesterol { get; set; }
        public string Sodium { get; set; }
        public string percentSodium { get; set; }
        public string Carbohydrates { get; set; }
        public string percentCarbohydrates { get; set; }
        public string Sugars { get; set; }
        public string Protein { get; set; }
        public string Caffeine { get; set; }
        public string percentCaffeine { get; set; }
        public string thanhPhan { get; set; }
        public int maLoai { get; set; }
        public string percentProtein { get; set; }
        public string ndTomTat { get; set; }
        public Nullable<int> idAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctDonHang> ctDonHangs { get; set; }
        public virtual loaiSP loaiSP { get; set; }
    }
}
